//! Deterministic Zig source emission for the narrow AOT prototype.
//!
//! Generated identifiers are derived only from definition numbers. Model names
//! are escaped string metadata and can never become Zig tokens.

const std = @import("std");
const aot_plan = @import("aot_plan.zig");

pub const GenerateError = error{
    OutOfMemory,
    SourceLimitExceeded,
};

/// Generates one complete, standalone Zig module. The caller owns the result.
pub fn generateAlloc(
    allocator: std.mem.Allocator,
    plan: *const aot_plan.Plan,
) GenerateError![]u8 {
    var output: std.Io.Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    const writer = &output.writer;

    emitHeader(writer, plan) catch return error.OutOfMemory;
    emitBound(writer, plan) catch return error.OutOfMemory;
    emitEvaluation(writer, plan) catch return error.OutOfMemory;

    if (output.written().len > plan.max_source_bytes) {
        return error.SourceLimitExceeded;
    }
    return output.toOwnedSlice() catch error.OutOfMemory;
}

fn emitHeader(writer: *std.Io.Writer, plan: *const aot_plan.Plan) !void {
    try writer.writeAll(
        \\//! Generated by Phaser's narrow model-specific AOT prototype.
        \\//! Do not edit: regenerate from the validated kernel program.
        \\
        \\const std = @import("std");
        \\const builtin = @import("builtin");
        \\
        \\pub const Scalar = f64;
        \\pub const Status = enum {
        \\    ok,
        \\    non_finite,
        \\    division_by_zero,
        \\    nonconvergent,
        \\    singular_derivative,
        \\};
        \\pub const WorkspaceLayout = struct { bytes: usize, alignment: usize };
        \\pub const CallError = error{
        \\    ShapeMismatch,
        \\    WorkspaceTooSmall,
        \\    WorkspaceMisaligned,
        \\    ForbiddenAliasing,
        \\    SizeOverflow,
        \\};
        \\pub const BindError = error{ShapeMismatch};
        \\pub const IdentityError = error{IdentityMismatch};
        \\
        \\pub const metadata = struct {
        \\
    );
    try writer.print(
        "    pub const format_version: u32 = {d};\n" ++
            "    pub const backend_version = \"{s}\";\n",
        .{ aot_plan.format_version, aot_plan.backend_version },
    );
    try emitFingerprint(writer, "model_fingerprint", plan.model_fingerprint);
    try emitFingerprint(writer, "request_fingerprint", plan.request_fingerprint);
    try emitNames(writer, "parameter_names", plan.parameter_names);
    try emitNames(writer, "background_names", plan.background_names);
    try writer.writeAll(
        \\    pub const target = .{
        \\        .architecture = builtin.cpu.arch,
        \\        .operating_system = builtin.os.tag,
        \\        .abi = builtin.abi,
        \\        .cpu_model = builtin.cpu.model.name,
        \\        .cpu_features = builtin.cpu.features,
        \\        .zig_version = builtin.zig_version,
        \\        .optimize_mode = builtin.mode,
        \\    };
        \\    pub const arithmetic_policy = "ordered_ieee_binary64";
        \\    pub const publication_policy = "point_atomic_non_finite";
        \\};
        \\
        \\pub fn validateIdentity(
        \\    expected_model: [32]u8,
        \\    expected_request: [32]u8,
        \\) IdentityError!void {
        \\    if (!std.mem.eql(u8, &expected_model, &metadata.model_fingerprint) or
        \\        !std.mem.eql(u8, &expected_request, &metadata.request_fingerprint))
        \\    {
        \\        return error.IdentityMismatch;
        \\    }
        \\}
        \\
        \\pub fn workspaceLayout(point_count: usize) WorkspaceLayout {
        \\    _ = point_count;
        \\    return .{ .bytes = 0, .alignment = 1 };
        \\}
        \\
    );
}

fn emitFingerprint(
    writer: *std.Io.Writer,
    name: []const u8,
    fingerprint: [32]u8,
) !void {
    try writer.print("    pub const {s} = [32]u8{{", .{name});
    for (fingerprint, 0..) |byte, index| {
        if (index != 0) try writer.writeAll(", ");
        try writer.print("0x{x:0>2}", .{byte});
    }
    try writer.writeAll("};\n");
}

fn emitNames(
    writer: *std.Io.Writer,
    name: []const u8,
    names: []const []const u8,
) !void {
    try writer.print(
        "    pub const {s} = [_][]const u8{{",
        .{name},
    );
    for (names, 0..) |value, index| {
        if (index != 0) try writer.writeAll(", ");
        try writer.print("\"{f}\"", .{std.zig.fmtString(value)});
    }
    try writer.writeAll("};\n");
}

fn emitBound(writer: *std.Io.Writer, plan: *const aot_plan.Plan) !void {
    try writer.writeAll("pub const Bound = struct {\n");
    for (0..plan.parameter_stage_count) |index| {
        try writer.print("    v{d}: Scalar,\n", .{index});
    }
    try writer.writeAll("};\n\n");
    try writer.writeAll("pub fn bind(parameters: []const Scalar) BindError!Bound {\n");
    try writer.print(
        "    if (parameters.len != {d}) return error.ShapeMismatch;\n",
        .{plan.parameter_count},
    );
    for (plan.nodes[0..plan.parameter_stage_count], 0..) |node, index| {
        try emitNode(writer, node, index, .bind);
    }
    try writer.writeAll("    return .{\n");
    for (0..plan.parameter_stage_count) |index| {
        try writer.print("        .v{d} = v{d},\n", .{ index, index });
    }
    try writer.writeAll("    };\n}\n\n");
}

const Stage = enum { bind, point, block };

fn emitNode(
    writer: *std.Io.Writer,
    node: aot_plan.Node,
    index: usize,
    stage: Stage,
) !void {
    const value_type = if (stage == .block) "Block" else "Scalar";
    switch (node) {
        .constant => |value| {
            if (stage == .block) {
                try writer.print(
                    "    const v{d}: Block = @splat(" ++
                        "@as(Scalar, @bitCast(@as(u64, 0x{x:0>16}))));\n",
                    .{ index, @as(u64, @bitCast(value)) },
                );
            } else {
                try writer.print(
                    "    const v{d}: Scalar = " ++
                        "@bitCast(@as(u64, 0x{x:0>16}));\n",
                    .{ index, @as(u64, @bitCast(value)) },
                );
            }
        },
        .parameter => |source| {
            try writer.print(
                "    const v{d}: {s} = parameters[{d}];\n",
                .{ index, value_type, source },
            );
        },
        .background => |source| {
            if (stage == .block) {
                std.debug.assert(source == 0);
                try writer.print(
                    "    const v{d}: Block = background.*;\n",
                    .{index},
                );
            } else {
                try writer.print(
                    "    const v{d}: Scalar = background[{d}];\n",
                    .{ index, source },
                );
            }
        },
        .negate => |operand| {
            try writer.print(
                "    const v{d}: {s} = -v{d};\n",
                .{ index, value_type, operand },
            );
        },
        .add => |operands| try emitVariadic(
            writer,
            index,
            operands,
            "+",
            value_type,
        ),
        .multiply => |operands| try emitVariadic(
            writer,
            index,
            operands,
            "*",
            value_type,
        ),
        .power_integer => |power| try emitPower(
            writer,
            index,
            power,
            value_type,
            stage == .block,
        ),
    }
}

fn emitVariadic(
    writer: *std.Io.Writer,
    index: usize,
    operands: []const aot_plan.DefinitionId,
    operator: []const u8,
    value_type: []const u8,
) !void {
    try writer.print(
        "    var v{d}: {s} = v{d};\n",
        .{ index, value_type, operands[0] },
    );
    for (operands[1..]) |operand| {
        try writer.print(
            "    v{d} {s}= v{d};\n",
            .{ index, operator, operand },
        );
    }
}

fn emitPower(
    writer: *std.Io.Writer,
    index: usize,
    power: aot_plan.IntegerPower,
    value_type: []const u8,
    vector: bool,
) !void {
    if (power.exponent == 0) {
        if (vector) {
            try writer.print(
                "    const v{d}: Block = @splat(@as(Scalar, 1.0));\n",
                .{index},
            );
        } else {
            try writer.print(
                "    const v{d}: {s} = 1.0;\n",
                .{ index, value_type },
            );
        }
        return;
    }
    if (vector) {
        try writer.print(
            "    var v{d}: Block = @splat(@as(Scalar, 1.0));\n" ++
                "    var f{d}: Block = v{d};\n",
            .{ index, index, power.base },
        );
    } else {
        try writer.print(
            "    var v{d}: {s} = 1.0;\n" ++
                "    var f{d}: {s} = v{d};\n",
            .{ index, value_type, index, value_type, power.base },
        );
    }
    var remaining = power.exponent;
    while (remaining != 0) {
        if (remaining & 1 != 0) {
            try writer.print("    v{d} *= f{d};\n", .{ index, index });
        }
        remaining >>= 1;
        if (remaining != 0) {
            try writer.print("    f{d} *= f{d};\n", .{ index, index });
        }
    }
}

fn emitEvaluation(writer: *std.Io.Writer, plan: *const aot_plan.Plan) !void {
    try writer.writeAll(
        \\inline fn trustedValue(bound: *const Bound, background: []const Scalar) Scalar {
        \\
    );
    for (0..plan.parameter_stage_count) |index| {
        try writer.print("    const v{d}: Scalar = bound.v{d};\n", .{ index, index });
    }
    for (
        plan.nodes[plan.parameter_stage_count..],
        plan.parameter_stage_count..,
    ) |node, index| {
        try emitNode(writer, node, index, .point);
    }
    try writer.print("    return v{d};\n", .{plan.output});
    try writer.writeAll("}\n\nconst Block = @Vector(4, Scalar);\n\n");
    try writer.writeAll(
        "inline fn trustedBlock(" ++
            "bound: *const Bound, background: *const [4]Scalar) Block {\n",
    );
    for (0..plan.parameter_stage_count) |index| {
        try writer.print(
            "    const v{d}: Block = @splat(bound.v{d});\n",
            .{ index, index },
        );
    }
    for (
        plan.nodes[plan.parameter_stage_count..],
        plan.parameter_stage_count..,
    ) |node, index| {
        try emitNode(writer, node, index, .block);
    }
    try writer.print("    return v{d};\n", .{plan.output});
    try writer.writeAll(
        \\}
        \\
        \\pub fn evaluateScalar(
        \\    bound: *const Bound,
        \\    background: []const Scalar,
        \\    workspace: []u8,
        \\    value: []Scalar,
        \\    status: []Status,
        \\) CallError!void {
        \\    return evaluateBatch(bound, background, 1, workspace, value, status);
        \\}
        \\
        \\pub fn evaluateBatch(
        \\    bound: *const Bound,
        \\    backgrounds: []const Scalar,
        \\    point_count: usize,
        \\    workspace: []u8,
        \\    values: []Scalar,
        \\    statuses: []Status,
        \\) CallError!void {
        \\    const background_count = std.math.mul(
        \\
    );
    try writer.print(
        "        usize, point_count, {d},\n",
        .{plan.background_count},
    );
    try writer.writeAll(
        \\    ) catch return error.SizeOverflow;
        \\    if (backgrounds.len != background_count or
        \\        values.len != point_count or
        \\        statuses.len != point_count)
        \\    {
        \\        return error.ShapeMismatch;
        \\    }
        \\    const layout = workspaceLayout(point_count);
        \\    if (workspace.len < layout.bytes) return error.WorkspaceTooSmall;
        \\    if (@intFromPtr(workspace.ptr) % layout.alignment != 0) {
        \\        return error.WorkspaceMisaligned;
        \\    }
        \\    try rejectAliasing(bound, backgrounds, workspace, values, statuses);
        \\
        \\    @setRuntimeSafety(false);
        \\    var point: usize = 0;
        \\    while (point_count - point >= 4) : (point += 4) {
        \\        const candidates = trustedBlock(
        \\            bound,
        \\            backgrounds[point..][0..4],
        \\        );
        \\        inline for (0..4) |lane| {
        \\            const candidate = candidates[lane];
        \\            if (std.math.isFinite(candidate)) {
        \\                values[point + lane] = candidate;
        \\                statuses[point + lane] = .ok;
        \\            } else {
        \\                statuses[point + lane] = .non_finite;
        \\            }
        \\        }
        \\    }
        \\    while (point < point_count) : (point += 1) {
        \\
    );
    try writer.print(
        "        const start = point * {d};\n" ++
            "        const candidate = trustedValue(\n" ++
            "            bound,\n" ++
            "            backgrounds[start .. start + {d}],\n" ++
            "        );\n",
        .{ plan.background_count, plan.background_count },
    );
    try writer.writeAll(
        \\        if (std.math.isFinite(candidate)) {
        \\            values[point] = candidate;
        \\            statuses[point] = .ok;
        \\        } else {
        \\            statuses[point] = .non_finite;
        \\        }
        \\    }
        \\}
        \\
        \\const Range = struct { start: usize, end: usize };
        \\
        \\fn sliceRange(slice: anytype) CallError!?Range {
        \\    if (slice.len == 0) return null;
        \\    const Child = std.meta.Elem(@TypeOf(slice));
        \\    const bytes = std.math.mul(usize, slice.len, @sizeOf(Child)) catch
        \\        return error.SizeOverflow;
        \\    const start = @intFromPtr(slice.ptr);
        \\    const end = std.math.add(usize, start, bytes) catch
        \\        return error.SizeOverflow;
        \\    return .{ .start = start, .end = end };
        \\}
        \\
        \\fn objectRange(pointer: anytype) CallError!?Range {
        \\    const Child = std.meta.Child(@TypeOf(pointer));
        \\    if (@sizeOf(Child) == 0) return null;
        \\    const start = @intFromPtr(pointer);
        \\    const end = std.math.add(usize, start, @sizeOf(Child)) catch
        \\        return error.SizeOverflow;
        \\    return .{ .start = start, .end = end };
        \\}
        \\
        \\fn overlaps(left: ?Range, right: ?Range) bool {
        \\    const a = left orelse return false;
        \\    const b = right orelse return false;
        \\    return a.start < b.end and b.start < a.end;
        \\}
        \\
        \\fn rejectAliasing(
        \\    bound: *const Bound,
        \\    backgrounds: []const Scalar,
        \\    workspace: []const u8,
        \\    values: []const Scalar,
        \\    statuses: []const Status,
        \\) CallError!void {
        \\    const ranges = [_]?Range{
        \\        try objectRange(bound),
        \\        try sliceRange(backgrounds),
        \\        try sliceRange(workspace),
        \\        try sliceRange(values),
        \\        try sliceRange(statuses),
        \\    };
        \\    for (ranges, 0..) |left, index| {
        \\        for (ranges[index + 1 ..]) |right| {
        \\            if (overlaps(left, right)) return error.ForbiddenAliasing;
        \\        }
        \\    }
        \\}
        \\
    );
}

const test_operands = [_]aot_plan.DefinitionId{ 0, 3 };
const test_nodes = [_]aot_plan.Node{
    .{ .parameter = 0 },
    .{ .parameter = 1 },
    .{ .parameter = 2 },
    .{ .background = 0 },
    .{ .multiply = &test_operands },
};
const test_parameter_names = [_][]const u8{
    "lambda",
    "m2",
    "omega\";\n@compileError(\"injected\")",
};
const test_background_names = [_][]const u8{"phi"};

fn planForTest() aot_plan.Plan {
    return .{
        .arena = undefined,
        .nodes = &test_nodes,
        .parameter_stage_count = 3,
        .output = 4,
        .parameter_count = 3,
        .background_count = 1,
        .model_fingerprint = [_]u8{0x11} ** 32,
        .request_fingerprint = [_]u8{0x22} ** 32,
        .parameter_names = &test_parameter_names,
        .background_names = &test_background_names,
        .max_source_bytes = 64 * 1024,
    };
}

test "AOT source is deterministic and model names remain escaped metadata" {
    var plan = planForTest();
    const first = try generateAlloc(std.testing.allocator, &plan);
    defer std.testing.allocator.free(first);
    const second = try generateAlloc(std.testing.allocator, &plan);
    defer std.testing.allocator.free(second);

    try std.testing.expectEqualSlices(u8, first, second);
    try std.testing.expect(
        std.mem.indexOf(
            u8,
            first,
            "\"omega\\\";\\n@compileError(\\\"injected\\\")\"",
        ) != null,
    );
    try std.testing.expect(
        std.mem.indexOf(u8, first, "\n@compileError(\"injected\")") == null,
    );
}

test "AOT source generation enforces its output bound atomically" {
    var plan = planForTest();
    plan.max_source_bytes = 1;
    try std.testing.expectError(
        error.SourceLimitExceeded,
        generateAlloc(std.testing.allocator, &plan),
    );
}

test "zero integer power emits no unused factor temporary" {
    const nodes = test_nodes ++ [_]aot_plan.Node{.{ .power_integer = .{
        .base = 4,
        .exponent = 0,
    } }};
    var plan = planForTest();
    plan.nodes = &nodes;
    plan.output = nodes.len - 1;
    const source = try generateAlloc(std.testing.allocator, &plan);
    defer std.testing.allocator.free(source);
    try std.testing.expect(
        std.mem.indexOf(u8, source, "const v5: Scalar = 1.0;") != null,
    );
    try std.testing.expect(
        std.mem.indexOf(u8, source, "const v5: Block = @splat") != null,
    );
    try std.testing.expect(std.mem.indexOf(u8, source, "f5") == null);
}

test "AOT source generation handles every allocation failure" {
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        generateForAllocationFailures,
        .{},
    );
}

fn generateForAllocationFailures(allocator: std.mem.Allocator) !void {
    var plan = planForTest();
    const source = try generateAlloc(allocator, &plan);
    defer allocator.free(source);
}
